import type {Metadata} from "next";
import {Roboto, Roboto_Slab} from 'next/font/google';
import "./globals.css";

const robo = Roboto({
  weight: ['400', '300'],
  subsets: ['latin'],
  display: 'swap',
});

const roboSlab = Roboto_Slab({
  weight: ['400', '700'], 
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto-slab',
});

export const metadata: Metadata = {
  title: 'Markdown Editor',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className={`${robo.className} ${roboSlab.variable}`}>{children}</body>
    </html>
  );
}