import type { Metadata } from "next";
import {Roboto_Mono } from 'next/font/google';
import { Roboto_Slab } from "next/font/google";
import "./globals.css";


const robo = Roboto_Mono({
  weight: ['400','300'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Markdown Editor',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={robo.className}>{children}</body>
    </html>
  );
}
